# Project: MCDream
# Makefile created by Embarcadero Dev-C++ 6.0

CPP      = g++.exe -D__DEBUG__
CC       = gcc.exe -D__DEBUG__
WINDRES  = windres.exe
RES      = MCDream_private.res
OBJ      = main.o $(RES)
LINKOBJ  = main.o $(RES)
LIBS     = -L"C:/D/downloads/CodeBlocks/share/CodeBlocks/MinGW64/lib" -L"C:/D/downloads/CodeBlocks/share/CodeBlocks/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc -g3
INCS     = -I"C:/D/downloads/CodeBlocks/share/CodeBlocks/MinGW64/include" -I"C:/D/downloads/CodeBlocks/share/CodeBlocks/MinGW64/x86_64-w64-mingw32/include" -I"C:/D/downloads/CodeBlocks/share/CodeBlocks/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"C:/D/downloads/CodeBlocks/share/CodeBlocks/MinGW64/include" -I"C:/D/downloads/CodeBlocks/share/CodeBlocks/MinGW64/x86_64-w64-mingw32/include" -I"C:/D/downloads/CodeBlocks/share/CodeBlocks/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"C:/D/downloads/CodeBlocks/share/CodeBlocks/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = MCDream.exe
CXXFLAGS = $(CXXINCS) -g3
CFLAGS   = $(INCS) -g3
DEL      = del /f /q

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${DEL} $(OBJ) $(BIN) 2>nul

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

main.o: main.cpp
	$(CPP) -c main.cpp -o main.o $(CXXFLAGS)

MCDream_private.res: MCDream_private.rc 
	$(WINDRES) -i MCDream_private.rc --input-format=rc -o MCDream_private.res -O coff 

